# Generated by Django 4.2 on 2023-04-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('code', models.CharField(help_text='Geef hier een code op', max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(help_text='Geef hier een naam op', max_length=50, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Geef hier een omschrijving op', null=True, verbose_name='Omschrijving')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('code', models.CharField(help_text='Geef hier een code op', max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(help_text='Geef hier een naam op', max_length=50, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Geef hier een omschrijving op', null=True, verbose_name='Omschrijving')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Geef hier een titel op', max_length=120, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Geef hier een omschrijving op', null=True, verbose_name='Omschrijving')),
                ('story_points', models.IntegerField(help_text='Geef hier het aantal story points op', verbose_name='Story points')),
                ('external_id', models.CharField(help_text='Geef hier optioneel een extern ID op', max_length=20, verbose_name='Externe ID')),
                ('project', models.ForeignKey(help_text='Geef hier het project voor het ticket op', on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Project')),
                ('ticket_type', models.ForeignKey(help_text='Geef hier het type ticket op', on_delete=django.db.models.deletion.PROTECT, to='projects.tickettype', verbose_name='Type ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
