# Generated by Django 4.2.1 on 2023-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_subproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='subproject',
            new_name='sub_project',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
    ]
