# Generated by Django 4.2 on 2023-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Geef de snippet een naam', max_length=100, verbose_name='Naam')),
                ('description', models.CharField(blank=True, help_text='Geef een korte omschrijving voor deze snippet', max_length=250, null=True, verbose_name='Omschrijving')),
                ('language', models.CharField(choices=[('html', 'HTML'), ('python', 'Python'), ('sql', 'SQL')], help_text='Geef hier de taal van de snippet op', max_length=6, verbose_name='Taal')),
                ('snippet', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
