# Generated by Django 4.2 on 2023-04-26 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(default=django.utils.timezone.now, help_text='Geef hier de starttijd op', verbose_name='Starttijd')),
                ('end_dt', models.DateTimeField(blank=True, help_text='Geef hier de eindtijd op', null=True, verbose_name='Eindtijd')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
                ('external_reference', models.CharField(blank=True, help_text='Geef hier een externe referentie op indien van toepassing', max_length=50, null=True, verbose_name='Externe referentie')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Tijdregistratie',
                'verbose_name_plural': 'Tijdregistraties',
            },
        ),
    ]
