# Generated by Django 4.2 on 2023-04-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeregistrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeregistration',
            name='user',
            field=models.ForeignKey(help_text='Selecteer de gebruiker', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker'),
        ),
    ]
