# Generated by Django 4.2 on 2023-04-27 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeregistrations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeregistration',
            name='start_dt',
        ),
        migrations.AddField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Geef hier de datum op', verbose_name='Datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeregistration',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Geef hier de starttijd op', verbose_name='Starttijd'),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='end_dt',
            field=models.TimeField(blank=True, help_text='Geef hier de eindtijd op', null=True, verbose_name='Eindtijd'),
        ),
    ]
