# Generated by Django 4.2 on 2023-04-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeregistrations', '0003_remove_timeregistration_start_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeregistration',
            old_name='end_dt',
            new_name='end_time',
        ),
    ]
