# Generated by Django 4.2 on 2023-04-27 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeregistrations', '0004_rename_end_dt_timeregistration_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeregistration',
            options={'ordering': ['start'], 'verbose_name': 'Tijdregistratie', 'verbose_name_plural': 'Tijdregistraties'},
        ),
        migrations.RemoveField(
            model_name='timeregistration',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeregistration',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeregistration',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timeregistration',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Geef hier de eindtijd op', null=True, verbose_name='Eindtijd'),
        ),
        migrations.AddField(
            model_name='timeregistration',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Geef hier de starttijd op', verbose_name='Starttijd'),
        ),
    ]
