# Generated by Django 4.2.1 on 2023-06-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timeregistrations', '0005_alter_timeregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeregistration',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.ticket', verbose_name='Ticket'),
        ),
    ]
