# Generated by Django 4.2.1 on 2023-06-03 12:55

from django.db import migrations
from django.utils import timezone


def convert_timeregistration_tickets(apps, schema_editor):
    TimeRegistration = apps.get_model("timeregistrations.TimeRegistration")
    Project = apps.get_model("projects.Project")
    Ticket = apps.get_model("projects.Ticket")
    TicketType = apps.get_model("projects.TicketType")
    # Only do the timeregistrations from april 2023 and later
    timeregistrations = TimeRegistration.objects.filter(
        start__date__gte=timezone.datetime(2023, 4, 1),
        external_reference__isnull=False
    ).exclude(external_reference="").values_list(
        "external_reference", flat=True
    )
    unique_references = set(list(timeregistrations))
    default_ticket_type = TicketType.objects.all().first()
    default_project = Project.objects.all().first()
    for reference in unique_references:
        ticket, created = Ticket.objects.get_or_create(
            external_id=reference,
            defaults={
                "project": default_project,
                "title": f"CHANGE TITLE: {reference}",
                "ticket_type": default_ticket_type,
                "description": "",
                "story_points": 99,
            }
        )
        TimeRegistration.objects.filter(external_reference=reference).update(
            ticket=ticket
        )


class Migration(migrations.Migration):

    dependencies = [
        ('timeregistrations', '0006_timeregistration_ticket'),
    ]

    operations = [
        migrations.RunPython(convert_timeregistration_tickets, reverse_code=migrations.RunPython.noop)
    ]
