# Generated by Django 4.2.1 on 2023-06-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_subproject'),
        ('timeregistrations', '0007_convert_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeregistration',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.subproject', verbose_name='Subproject'),
        ),
    ]
