# Generated by Django 4.2.1 on 2023-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeregistrations', '0008_timeregistration_sub_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeregistration',
            name='project',
        ),
    ]
