# Generated by Django 4.2.1 on 2023-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeregistrations', '0009_remove_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeregistration',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duur'),
        ),
    ]
