# Generated by Django 4.2.1 on 2023-06-04 13:19

from django.db import migrations
from django.db.models import F, Q


def fill_duration_fields(apps, schema_editor):
    TimeRegistration = apps.get_model("timeregistrations.TimeRegistration")
    time_registrations = TimeRegistration.objects.filter(
        Q(end__isnull=False) & Q(start__isnull=False)
    )
    time_registrations.update(duration=F("end") - F("start"))


class Migration(migrations.Migration):
    dependencies = [
        ("timeregistrations", "0010_timeregistration_duration"),
    ]

    operations = [
        migrations.RunPython(
            fill_duration_fields, reverse_code=migrations.RunPython.noop
        )
    ]
