# Generated by Django 4.2.1 on 2023-06-04 15:02

from django.db import migrations
from django.db.models import Q, F


def fill_sub_projects(apps, schema_editor):
    TimeRegistration = apps.get_model("timeregistrations.TimeRegistration")
    time_registrations = TimeRegistration.objects.filter(
        Q(sub_project__isnull=True) & Q(ticket__isnull=False)
    )
    for tr in time_registrations:
        tr.sub_project = tr.ticket.sub_project
        tr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("timeregistrations", "0011_auto_20230604_1519"),
    ]

    operations = [
        migrations.RunPython(fill_sub_projects, reverse_code=migrations.RunPython.noop)
    ]
